### ISSUE TITLE
Section Type 7(CONFIGURATION) being returned for a Libvirt QEMU Suspend image

### ISSUE THREAD

**Issue by Arnab035** [juergh/lqs2mem.py#1]
Hi,

I am having a problem trying to convert a Libvirt QEMU Suspend image to a Raw RAM Image format. 

I am currently running the below command to perform this activity --
`lqs2mem.py -v ~/mem.qcow2`

where **mem.qcow2** is the Libvirt Suspend Image file that I have. I have obtained this snapshot after "pausing" QEMU-KVM.

I am not able to read in the specific sections of the image file(like **pc.ram**). So the conversion is not successful at all as the **verbose** output returns the section-type as 7 (`QEMU_CONFIGURATION`) instead of other section types like `QEMU_VM_SECTION_START`.

Why is this happening ? Is there a mistake while recording the snapshot ?

Please suggest some steps on how to handle this problem.

**Comment by juergh** [comment]
Sorry for the late reply, was on vacation. This is because lqs2mem can't handle newer QEMU images. They introduced a CONFIG section that comes before the stored memory which lqs2mem trips over. I haven't found the time yet to add support for that.

**Comment by Arnab035** [comment]
Hi Juergh,

Thanks for the reply. Yes I could see that -- lqs2mem always ends up stopping in the CONFIG section of the QEMU image. Anyway I have obtained an ELF image of the QEMU disk image. 

I will close this issue since I have the ELF image of the memory.
